# Site settings
title: "Joy Blog"
email: 442114687@qq.com
description: "A blog for Joy made by Jekyll."
baseurl: ""
url: "https://zhengjynicolas.github.io/"
title_description: "Welcome to my blog. I am Joy Zheng, a web frontend developer. Making this blog for learning and sharing. Hope you like here and maybe give me some of your advice."
title_image: "https://avatars2.githubusercontent.com/u/32067765?s=460&v=4"
google_analytics: ""
disqus_account: zhengjynicolas.github.io
github_repository: https://github.com/zhengjynicolas/zhengjynicolas.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  zhengjynicolas
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"javascript:;\">Joy Zheng</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/zhengjynicolas\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
